export const ACTION = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  INIT_NEW_USER: 'INIT_NEW_USER',
  USER_COMPLETED_LEVEL: 'USER_COMPLETED_LEVEL',
  USER_FAILED_LEVEL: 'USER_FAILED_LEVEL',
  RESET_USERS_GAME: 'RESET_USERS_GAME',
};

export const SCORE_PROPERTIES = {
  LEVEL: 'level',
  ALL_TIMES: 'allTimes',
  COUNT: 'count',
};
